# -*- coding: utf-8 -*-
s="""
Chapter Questions and Answers 
Chapter 1: 
1.  What was the unidentified aircraft at the beginning of the story? (a pilot-intraining that made an error) 
2.  What did they do with the pilot? (released him) 
3.  What is the main character’s name? (Jonas) 
4.  What was his best friend’s name? (Asher) 
5.  What month did the story begin? (almost December) 
6.  What was the ritual that Jonas’s familydid at the end of their evening meal? (telling of feelings) 
7.  What was Jonas’s father’s job? (a nurturer: responsible for all the physical and emotional needs for every newchild) 
8.  How many children could each family have? (2: one girl and one boy) 
9.  What was Jonas apprehensive about? (the Ceremony of Twelve) 
Chapter 2: 
1.  People receive their babies at what ceremony? (The Ones) 
2.  What was the name of the baby that the father was so concerned about? (Gabriel or Gabe) 
3.  What was Jonas’s sister’s name? (Lily) 
4.  How old did you have to be to get your first bicycle? (9) 
5.  What rule was almost always broken by the community and wasn’t taken seriously? (Older brothers and sisters secretly taught the younger ones to ride a bicycle) 
6.  What is the most important job in the community? (the Receiver or Committee of Elders) 
7.  Why was the Ceremony of Twelves the most important ceremony? (people were given their Life Assignment) 
8.  How did their lives change after the Ceremony of 12’s? (no recreation time, being trained) 
9.  What was Lily’s comfort object? (stuffed elephant) 
10. What was Jonas’s comfort object? (a bear) 
Chapter 3: 
1.  What was so different about the newchild? (He had pale eyes like Jonas. Most citizens had dark eyes.) 
2.  What was the newchild’scomfort object? (hippo) 
3.  How many years could you serve as a birth mother? (3 years or 3 births) 
4.  What did you do after being a birth mother? (became laborers) 
5.  What had Jonas taken from the Recreation Area and was reminded by public announcement that he was not to do that? (an apple) 
6.  What was it about the apple that concerned Jonas? (The appearance of it changed for a brief second three or four times.) 
7.  What were Jonas and Asher doing to the apple? (tossing it back and forth) 
8.  Why was the new child, Gabriel, staying with Jonas’s family unit? (The father was concerned about him. He was fussy and didn’t seem to be developing as fast as the others. He was trying to avoid the possibility of releasing him.) 
Chapter 4: 
1.  What did Benjamin do for his volunteerhours? (worked at the Rehabilitation Center) 
2.  What did Lily do for her volunteer hours? (worked at the Childcare Center) 
3.  Where did Asher and Fiona work? (in the House of Old) 
4.  What did Jonas help do at the House of Old? (bathe old people) 
5.  What celebrations did they have at the House of Old? (the release of individual patients) 
6.  What do they do at the celebrations? (the telling of the life, toast, cheers, chanting of anthem, and lovely goodbye speeches) 
7.  Where do they go when one has been released? (no one knows) 
8.  How did Roberto look when he walked through the door of the Releasing Room? (He bowed to them and had a look of pure happiness on his face.) 
Chapter 5: 
1.  What was the morning ritual for Jonas’s family? (the telling of dreams) 
2.  What dream did Jonas tell his family he had? (He wanted Fiona to get in the tub so he could bathe her.) 
3.  The mother had an explanation for the dream. What was it? (His first feelings of “Stirrings.” 
4.  What was the treatment? (to take pills) 
5.  Who all has to take these pills? (Anyone who has stirrings. Eventually, everyone has to take the pills.) 
6.  How long does one have to take these pills? (Until one enters the House of Old) 
7.  How did Jonas feel about taking the pills? (He was proud to have joined those who are taking the pills.) 
8.  How did Jonas feel about the stirrings? (He found them pleasurable, and wished he could feel them again.) 
Chapter 6: 
1.  Fours, fives, and sixes had to wear jackets that were buttoned down their backs. What was that to teach them? (interdependence) 
2.  Sevens wore a jacket that was buttoned down the front. What did that represent? (the first sign of independence) 
3.  Nines got their first bicycle. What did that represent? (moving gradually out to the community, away from the protective family unit) 
4.  Why was a replacement child given for the four year old Caleb? (He had fallen in a river and died.) 
5.  Lily went through the Eights ceremony. What did the pockets on her jacket represent? (that she was old enough tokeep track of her own things) 
6.  What was special about turning 10? (children got their hair cut) 
7.  If you wanted to leave the community, where would you go? (to Elsewhere, to be released) 
8.  How did people get a spouse? (Spouses were matched after being carefully monitored by the Committee of Elders.) 
Chapter 7: 
1.  What was Jonas’s number? (19, technically 11-19) 
2.  At what age would your age no longer matter? (12) 
3.  Why did Asher get smacked a lot when he was a three? (He kept saying “smack” instead of “snack.”) 
4.  Why did Jonas get so upset during the Ceremony of 12? (His turn was skipped over when giving assignments.) 
5.  What was Asher’s assignment? (Caretaker in House of the Old) 
6.  What reason did Jonas think was why he was skipped? (He must have done something wrong.) 
7.  What was Jonas’s reaction? (tried tomake himself smaller in his seat) 
Chapter 8: 
1.  Jonas had not actually been assigned, but he was ______________. (selected) 
2.  What was Jonas to be selected for? (Receiver of Memory) 
3.  Who will train Jonas? (the current Receiver of Memory) 
4.  The characteristics for a Receiver of Memory are intelligence, integrity, and ________________. (courage, wisdom, or the capacity to see beyond) 
5.  How did Jonas respond? (unsure, confused atfirst, but agreed that he had these qualities) 
6.  When he looked out at the audience, what happened? (something changed) 
7.  How did the audience respond to Jonas left standing on the stage (They chanted his name.) 
8.  Why was he filled with fear? (He did not know what thisnew role would bring or what it meant.) 
Chapter 9: 
1.  Why did things seem so tense for Jonas after the ceremony? (People seem to be treating him differently.) 
2.  What kind of job did Jonas get? (Receiver of Memory, the most important job of the community) 
3.  What happened to the girl that was supposed to have been trained for the Receiver of Memory job? (She failed – they don’t know what happened to her – she disappeared.) 
4.  What was in Jonas’s instruction folder? (One sheet – 8 instructions) 
5.  How much recreation time was he allowed? (none) 
6.  What was the final rule on his sheet of instructions? (You may lie.) 
7.  Was he allowed medication? (Only if it was not related to his training.) 
8.  What realization struck him? (Everyone might be lying.) 
Chapter 10: 
1.  What was different about the bikes after the Twelves Ceremony? (the name plate was changed to citizen-in-training) 
2.  Why was the Receiver of Memory’s doors locked? (He didn’t want to be disturbed by foolish things, he needed to concentrate.) 
3.  How was the furniture different in the office? (It wasn’t standardized like the community’s furniture.) 
4.  Why was Jonas so surprised to see all the books in the office? (He’d never seen a book, except for a dictionary, community map, and Rules book.) 
5.  What memories did the Receiver want Jonas to have? (memories of the whole world) 
6.  What analogy did the Receiver compare his life to? (going down a hill on a sled in deep snow) 
7.  What did Jonas have to do to get his first memory? (take his tunic off, lay face down on the couch) 
8.  What memory did the Receiver give to Jonas? (snow) 
Chapter 11: 
1.  For the first time, Jonas experienced the feel of ___________. (snow) 
2.  He felt himself sitting on a _________. (sled) 
3.  He was on top of a mound, or __________. (hill) 
4.  What happens to the memory once the Giver gives it away to Jonas? (The Giver no longer has the memory) 
5.  Why was there no longer snow? (Climate Control) 
6.  Why did the leaders go to “sameness?” (practical, convenient) 
7.  The second memory was warm and comforting. What was it? (sunshine) 
8.  What was the last memory given to Jonah in this chapter? (sunburn) 
Chapter 12: 
1.  What dream did Jonas continue having? (riding down a hill on a sled) 
2.  Why did Jonas feel uncomfortable listening to all the twelves about their first day of training? (because he was not allowed to discuss his) 
3.  What weird thing keeps happening to Jonas? (things change for an instant) 
4.  The Giver told him that Jonas was experiencing ___________. (the color, red) 
5.  Why did colors disappear intheir society? (the people made the choice to go to sameness, did away with differences) 
6.  To help Jonas understand the concept of color, the Giver wants to give him the memory of a ____________. (rainbow) 
7.  Does Fiona like her new job? (yes) 
8.  What red things has Jonas seen so far? (apple, Fiona’s hair, books, sled) 
Chapter 13: 
1.  Why was the community without color? (no choices, sameness, scientists changed genes to make everything look flat and hueless) 
2.  Why couldn’t the community have choices? (they might make a mistake) 
3.  Jonas tried to get Asher to see the color ________ in geraniums. (red) 
4.  What horrible memory did the Giver give toJonas this time? (an elephant killed for its tusks and the baby elephant crying for its mama) 
5.  Why would it be difficult for Jonas to havea spouse? (He couldn’t really share his life with her.) 
6.  What happened 10 years ago? (When the Receiver failed, the memories were released out into the community.) 
7.  Why was it important that the Receiver keep all the memories? (so that the citizens wouldn’t have to bear the pain) 
8.  Jonas told the Receiver to start givinghim some painful memories? Why? (to lighten the Receiver’s load because he was in so much pain) 
Chapter 14: 
1.  How was the second snow/sled experience different from the first? (colder, steeper, not falling as thickly, hard, bluish ice, runners wouldn’t slide, terrified, felt pain from a broken leg) 
2.  Was he given any medications for the pain? (no) 
3.  Every day, Jonas was given a memory of pain, but ended with a ________________. (a color-filled memory of pleasure) 
4.  Why does the Receiver have to hold all the painful, terrible memories? (for wisdom) 
5.  Why didn’t the elders decide to allow birthmothers havefour babies instead of three? (because of the memory of hunger) 
6.  What was Gabriel’s main problem? (He was fretful at night.) 
7.  What did they do when a birthmother had twins? The smaller one was released.) 
8.  How did Jonas calm down Gabriel? (He gave him a memory of sailing.) 
Chapter 15: 
1.  What was wrong with the Giver? (He was suffering from the pain of too many horrible memories.) 
2.  What was the memory? (war) 
Chapter 16: 
1.  What were some of the good memories thatwere given to Jonas? (a birthday party, visited museums, horseback riding, animal/human bonds) 
2.  What was the Giver’s favorite memory that was given away? (Christmas, family, grandparents) 
3.  What new feeling did Jonas get to experience? (love) 
4.  Why did Jonas feel that love would berisky? (order would fall apart) 
5.  What happened when Gabriel was taken away from Jonas? (Gabe cried again) 
6.  What did Jonas do at the end? (threw his pill away) 
Chapter 17: 
1.  What has happened to Jonas since he has stopped taking his pills? (the stirrings had returned) 
2.  What did Jonas want to do on his unexpected holiday? (play, ride his bike) 
3.  He found his friends. What were they playing? (war) 
4.  What happened with the war game? (Jonas was upset, couldn’t play, the others decided to stop playing and left) 
5.  What would the father do the next day when the identical twins were born? (weigh them, keep the heavier one, release the other one) 
6.  How does the father describe the release? (cleans him up and gets him comfy, performs a small ceremony of Release, then waves bye bye) 
7.  Who takes the baby when it is released, according to father? (somebody from Elsewhere) 
8.  What job did mother think would fit Lily? (storyteller) 
Chapter 18: 
1.  What was the last Receiver’s-in-training name? (Rosemary) 
2.  What was the cause of her failure? (couldn’t bear the pain of the memories that created anguish) 
3.  Where did she go? (asked to be released) 
4.  What happened to the memories when Rosemary died? (They came back to the people.) 
5.  For the first time, the community had memories which caused them to have ____________. (feelings) 
6.  What did the Giver do to help the people? (nothing, hewas devastated) 
7.  Why did the Giver keep telling Jonas to stayaway from the river? (He didn’t want him to die because the memories would go to the people.) 
8.  How does Jonas deal with the memories? (He relies on the Giver to help him.) 
Chapter 19: 
1.  Jonas decided that he wanted to watch a __________. (release) 
2.  How was Jonas able to watch one? (He was shown a video of the release of the twin.) 
3.  Where did Jonas’s father stick the needle into the newborn twin? (on top of forehead) 
4.  What does it mean to be released? (you are killed) 
5.  Where did father place the baby? (in a carton) 
6.  How was Rosemary released? (She injected herself.) 
7.  What was Jonas’s reaction to all of this? (He wanted to cry and throw up.) 
Chapter 20: 
1.  Jonas was very upset when he figured outthat to be “released” meant to be _____________. (killed) 
2.  Where did he spend that night? (with the Giver) 
3.  Who all in the community gets released? (one twin, the old, those who ask, those who break rules 3 times) 
4.  Jonas and the Giver came to the conclusion that the community needed to ____________. (change) 
5.  What was the plan? (Jonas would run away to Elsewhere.) 
6.  What time of day or night would Jonas leave? (middle of night) 
7.  What would the Giver tell the community happened to Jonas? (fell into the river) 
8.  Who is the Giver’s daughter? (Rosemary) 
Chapter 21: 
1.  What decision was made about Gabriel? (to be released) 
2.  What crimes did Jonas commit when he left? (leaving at night, stealing food, stole father’s bicycle, took Gabriel) 
3.  What did they do the first day after breakfast? (hid and slept) 
4.  What time of day did Jonas and Gabe travel? (at night) 
5.  Why couldn’t the search planes see them? (They don’t see color, so they blended in with their surroundings.) 
6.  Why did Jonas make himself and Gabe coldas the search planes hunted for them? (to throw the heat detectors off) 
7.  How did Jonas know that the community was starting to give up the search? (The search planes were coming more infrequently.) 
Chapter 22: 
1.  How did the landscape change? (narrow, bumpy roads) 
2.  Now that the fear of searchers was gone, what did Jonas fear now? (the unknown) 
3.  What had Gave mistaken in the air? (He thought a bird was a plane.) 
4.  There was a desperate fear building in him.What was it? (He was afraid that he and Gabe would starve.) 
5.  Did Jonas want to return to the community? (not really) 
6.  What part of the body did Jonas hurt? (his ankle) 
7.  Why were Jonas and Gabe crying? (They were cold, wet, hungry, weak) 
8.  What other reason was Jonas crying? (He was afraid that he would no longer be able to save Gabriel.) 
Chapter 23: 
1.  How did Jonas try to warm up Gabe? (He gave him a memory of sunshine.) 
2.  Why was it so difficult to travel? (It was snowing heavily.) 
3.  Why did he suddenly become happy? (He was remembering happy times – his family, the Giver) 
4.  What was waiting for him at the top of the hill? (a sled) 
5.  What was the first thing that Jonas saw in Elsewhere? (Christmas lights) 
6.  What did he hear for the first time? (music) 
7.  How did he know this place would take care of Gabe and him? (He felt it, an unknown feeling) 
8.  What do you think happened? (answers vary) 
"""
import re
print re.sub("\(.+\)","",s)
#print re.sub("\(.+\n?.+\)","",s)
qs = re.findall("\d+\..+",s)
# for q in qs:
# 	print q

questions = [(re.sub("(\(.+\n?.+\))","",q),re.findall("\((.+)\)",q)) for q in qs]
#print qs
#print questions


import random
for x in range(5):
	question,a = random.choice(questions)
	print question
	print a[0]	
	choices = [y[0] for x,y in questions if y !=a and len(y)>0]
	random.shuffle(choices)
	print '\n'.join(choices[:3])


#print len(re.findall("(\n\d.+\n?.+)\n\d",s))
