# -*- coding: utf-8 -*-
from question import Question, Packet
class lit_Question(Question):
	def __init__(self,name,examples):
		Question.__init__(self,name,examples=examples)
		self.all_types = ["personification","simile","metaphor","hyperbole"]
		self.qsection="Literary Devices"
		self.qprompt = "Identify the best literary device used in the sentence below:"

def make_packet(number=1,fn_list=[]):
	""" makes packet for questions """
	sm_qs = [
	"Comparison between two unlike things using like or as.",
	"My love is like a red, red rose.",
	"You were as brave as a lion.",
	"They fought like cats and dogs.",
	"He is as funny as a barrel of monkeys.",
	"This house is as clean as a whistle.",
	"He is as strong as an ox.",
	"Your explanation is as clear as mud.",
	"Watching the show was like watching grass grow.",
	"That is as easy as shooting fish in a barrel.",
	"This contract is as solid as the ground we stand on.",
	"That guy is as nutty as a fruitcake.",
	"Don’t just sit there like a bump on a log.",
	"That went over like a lead balloon.",
	"They are as different as night and day.",
	"She is as thin as a toothpick.",
	"Last night, I slept like a log.",
	"This dress is perfect because it fits like a glove.",
	"They wore jeans, which made me stand out like a sore thumb.",
	"My love for you is a deep as the ocean.",
	"I am so thirsty, that my throat is as dry as a bone.",
	"As bold as brass.",
	"As bright as a button.",
	"As shiny as a new pin.",
	"As cold as ice.",
	"As common as dirt.",
	"As cool as a cucumber.",
	"As hard as nails.",
	"As hot as hell.",
	"As innocent as a lamp.",
	"As large as life.",
	"As light as a feather.",
	"As tall as a giraffe.",
	"As tough as nails.",
	"As white as a ghost.",
	"As sweet as sugar.",
	"As sure as death and taxes.",
	]
	mr_qs =[
	"Comparison between two unlike things not using like or as.",
	"Success is a sense of achievement, it is not an illegitimate child!",
	"She is the light of my life.",
	"Time is a thief.",
	"Dave is a bad apple.",
	"His face was a blue moon pocked with craters.",
	"She is a fox.",
	"Conscience is a man’s compass.",
	"All religions, arts, and sciences are branches of the same tree.",
	"True friends stab you in the front.",
	"America is a melting pot. ",
	"The snow is a white blanket. ",
	"America is a melting pot.  ",
	"Her lovely voice was music to his ears. ",
	"Life is a rollercoaster.  ",
	"The alligator’s teeth are white daggers.  ",
	"Their home was a prison. ",
	"His heart is a cold iron.",
	"She is a peacock.",
	"He is a shining star. ",
	"Time is money.",
	"My teacher is a dragon.",
	"Tom’s eyes were ice.",
	"The detective’s face was wood as he listened to her story.",
	"She feels that life is a fashion show.",
	"The world is a stage.",
	"My kid’s room is a disaster area.",
	"The children were flowers grown in concrete gardens.",
	"Kisses are the flowers of affection.",
	"His words were cotton candy.",
	"Mary’s eyes were fireflies.",
	"John’s suggestion was just a Band-Aid.",
	"The cast on his broken leg was a plaster shackle.",
	"Jane’s ambitions are a house of cards.",
	"Her long hair was a flowing golden river.",
	"The computers at school are old dinosaurs.",
	"Laughter is the music of the soul.",
	"He is a night owl.",
	"Maria is a chicken.",
	"The falling snowflakes are dancers.",
	"With his new haircut, he was a sheepdog.",
	"At five o’clock, the interstate was a parking lot.",
	"Books are keys to your imagination.",
	"Her teddy bear was her best friend, never telling her secrets.",
	"The peaceful lake was a mirror.",
	"Terry was blue when his goldfish died.",
	"The wind was an angry witch.",
	"The ballerina was a swan, gliding across the stage.",
	"Her angry words were bullets to him.",
	"Your brain is a computer.",
	"Jamal was a pig at dinner.",
	"You are my sunshine.",
	"The car was a furnace in the sun.",
	"Thank you so much. You are an angel.",
	"That coach is an ogre.",
	"Ben’s temper was a volcano, ready to explode.",
	"The kids were monkeys on the jungle gym.",
	"The sun is a golden ball.",
	"The clouds are balls of cotton.",
	"Sue’s room is a zoo with fish, a gerbil and a parakeet.",
	"The park was a lake after the rain.",
	"The lightning was fireworks in the sky.",
	"Gary is a mule.",
	"That lawn is a green carpet.",
	"My dad is a road hog.",
	"The stars are sparkling diamonds.",
	"Those two best friends are two peas in a pod.",
	"He is a walking dictionary.",
	"Donations for the popular charity were a tsunami.",
	"Necessity is the mother of invention.",
	"My big brother is a couch potato.",
	"The road was a ribbon stretching across the desert.",
	"The teenager’s stomach was a bottomless pit.",
	"The thunder was a mighty lion.",
	"I am so excited. My pulse is a race car.",
	"The moon is a white balloon.",
	"Toddlers are rug rats.",
	"The stormy ocean was a raging bull.",
	"Her tears were a river flowing down her cheeks.",
	]

	ps_qs = [
	"Using human characteristics, qualities or activities to describe non-living things.",
	"The stars danced playfully in the moonlit sky.",
	"The run down house appeared depressed.",
	"The first rays of morning tiptoed through the meadow.",
	"She did not realize that opportunity was knocking at her door.",
	"He did not realize that his last chance was walking out the door.",
	"The bees played hide and seek with the flowers as they buzzed from one to another.",
	"The wind howled its mighty objection.",
	"The snow swaddled the earth like a mother would her infant child.",
	"The river swallowed the earth as the water continued to rise higher and higher.",
	"Time flew and before we knew it, it was time for me to go home.",
	"The ocean waves lashed out at the boat and the storm continued to brew.",
	"My computer throws a fit every time I try to use it.",
	"The thunder grumbled like an old man.",
	"The flowers waltzed in the gentle breeze.",
	"Her life passed her by.",
	"The sun glared down at me from the sky.",
	"The moon winked at me through the clouds above.",
	"The wind sang through the meadow.",
	"The car was suffering and was in need of some TLC.",
	"At precisely 6:30 am my alarm clock sprang to life.",
	"The window panes were talking as the wind blew through them.",
	"The ocean danced in the moonlight.",
	"The words appeared to leap off of the paper as she read the story.",
	"The phone awakened with a mighty ring.",
	"The funeral raced by me in a blur.",
	"While making my way to my car, it appeared to smile at me mischievously.",
	"The car, painted lime green, raced by screaming for attention.",
	"The butterflies in the meadow seemed to two-step with one another.",
	"The waffle jumped up out of the toaster.",
	"The popcorn leapt out of the bowl.",
	"When the DVD went on sale, it flew off the shelves.",
	"I tripped because the curb jumped out in front of me.",
	"Time creeps up on you.",
	"The news took me by surprise.",
	"The fire ran wild.",
	"The thunder clapped angrily in the distance.",
	"The tornado ran through town without a care.",
	"The door protested as it opened slowly.",
	"The evil tree was lurking in the shadows.",
	"The tree branch moaned as I swung from it.",
	"Time marches to the beat of its own drum.",
	"The storm attacked the town with great rage.",
	"My life came screeching to a halt.",
	"The baseball screamed all the way into the outfield.",
	"The blizzard swallowed the town.",
	"The tsunami raced towards the coastline.",
	"The avalanche devoured everything in its path.",
	"The pistol glared at me from its holster.",
	"The car beckoned me from across the showroom.",
	"I could hear Hawaii calling my name.",
	]
	hy_qs = [
	"Using an extreme exaggeration to compare things.",
	"I am so hungry I could eat a horse.",
	"I have a million things to do.",
	"I had to walk 15 miles to school in the snow, uphill.",
	"I had a ton of homework.",
	"If I can’t buy that new game, I will die.",
	"He is as skinny as a toothpick.",
	"This car goes faster than the speed of light.",
	"That new car costs a bazillion dollars.",
	"We are so poor; we don’t have two cents to rub together.",
	"That joke is so old, the last time I heard it I was riding on a dinosaur.",
	"They ran like greased lightning.",
	"He's got tons of money.",
	"You could have knocked me over with a feather.",
	"Her brain is the size of a pea.",
	"He is older than the hills.",
	"The skin on her face was as thin and drawn as tight as the skin of onion and her eyes were gray and sharp like the points of two picks.",
	"It was not a mere man he was holding, but a giant; or a block of granite. The pull was unendurable. The pain unendurable.",
	"People moved slowly then. There was no hurry, for there was nowhere to go, nothing to buy and no money to buy it with, nothing to see outside the boundaries of Maycomb County.",
	"It's a slow burg. I spent a couple of weeks there one day.",
	"Why does a boy who’s fast as a jet take all day and sometimes two to get to school?",
	]
	ir_qs=[
	"Irony",
	
	]
	qdict = dict(zip(["simile","metaphor","personification","hyperbole"],[sm_qs,mr_qs,ps_qs,hy_qs]))
	simile = lit_Question("simile",sm_qs)
	personification = lit_Question("personification",ps_qs)
	metaphor = lit_Question("metaphor",mr_qs)
	#hyperbole = Question("hyperbole",qdict = qdict,qsection="Literary Devices",qprompt="Identify the type of passage below:")
	hyperbole = lit_Question("hyperbole",hy_qs)
	fn_list= [simile,metaphor,personification,hyperbole]
	return Packet(fn_list).make_packet(number)

if __name__=="__main__":
	print "testing..."
	exs = ["The hills are leering at me with their eyes they were."]
	q= lit_Question("personification",exs)
	assert q.get_example()
	assert len(q.get_Question().split("\t"))==7,"size is not 7 should be 1 prompt, 1 passage, 1 sentence, 4 options"
	print "EX",q.get_example()
	print "QUESTION",q.get_Question()
	packet = make_packet(5)
	print packet
	print"CHOICES",[s.split("\t")[3:4] for s in packet.strip().split("\n")]
