from question import make_packets
"""pronouns id"""
def make_packet(n=1):
	return make_packets(n,qdict={
		"Relative Pronoun":[
		"The cake <u>that</u> we baked was delicious.",
		"That day the sun, <u>which</u> covered over the entire planet, was blazing and very bright!",
		"The person <u>who</u> phoned me last night is my teacher.",
		"The person <u>that</u> phoned me last night is my teacher.",
		"The car <u>which</u> hit me was yellow.",
		"The car <u>that</u> hit me was yellow.",
		"The student <u>whose</u> phone just rang should stand up.",
		"Students <u>whose</u> parents are wealthy pay extra.",
		"Mr Bilbo, <u>whom</u> I like very much, is my teacher.",
		],
		"Intensive Pronoun":[
		"Freddie <u>himself</u> asked Julie out.",
		"The robot <u>itself</u> found a way to be happy among the humans.",
		"I <u>myself</u> am tired of doing homework.",
		"The president <u>himself</u> appeared at the rally.",
		"My sister made the bread <u>herself</u>.",
		"She found the treasure <u>herself</u>.",
		"I have never yet failed to meet a deadline I <u>myself</u> have set up.",
		],
		"Reflexive Pronoun":[
		"Allison accidentally cut <u>herself</u>.",
		"I saw <u>myself</u> reflected in her eyes.",
		"They psyched <u>themselves</u> up for the football game.",
		"The girls talked to <u>themselves</u> about the disturbing matter at school.",
		"They girls and boys joked with <u>themselves</u> about the incident at school.",
		"We bought <u>ourselves</u> pretzels at the fair.",
		"My brother made <u>himself</u> some dinner.",
		"You should buy <u>yourself</u> a new computer.",
		],
		"Demonstrative Pronoun":[
		"<u>That</u> is a good idea!",
		"<u>Those</u> are my friends.",
		"<u>This</u> tastes good.",
		"Have you seen <u>this</u>?",
		"<u>These</u> are bad times.",
		"Do you like <u>these</u>?",
		"<u>That</u> is beautiful.",
		"Look at <u>that</u>!",
		"<u>Those</u> were the days!",
		"Can you see <u>those</u>?",
		"These are bigger than <u>those</u>.",
		"This is heavier than <u>that</u>.",
		],
		"Personal Pronoun":[
		"<u>She</u> was very much appalled at the rude behavior of her classmates.",
		"During the night, <u>I</u> found the boy sitting near the fireplace.",
		"<u>I</u> like coffee.",
		"John helped <u>me</u>.",
		"Do <u>you</u> like coffee?",
		"John loves <u>you</u>.",
		"<u>He</u> runs fast.",
		"Did Ram beat <u>him</u>?",
		"<u>She</u> is clever.",
		"Does Mary know <u>her</u>?",
		"<u>It</u> doesn't work.",
		"Can the man fix <u>it</u>?",
		"<u>We</u> went home.",
		"Anthony drove <u>us</u>.",
		"Do <u>you</u> need a table for three?",
		"Did John and Mary beat <u>you</u> at doubles?",
		"<u>They</u> played doubles.",
		"John and Mary beat <u>them</u>.",
		],
		"Possessive Pronoun":[
		"She owned <u>her</u> own shop in the middle of the dragon lair and sold all manner of dragon-scaled trinkets.",
		"They found <u>their</u> ship to be in ruin after the storm.",
		"He did not fancy having <u>his</u> sword taken in the goblin's lair.",
		"Sarah and John missed <u>their</u> bus.",
		"<u>My</u> father and I haven't ever camped beside a river.",
		"I saw <u>her</u> book on your table.",
		"<u>His</u> hair is longer than hers.",
		"<u>My</u> dog is better than their dog.",
		"The kids are <u>yours</u>, mine, and ours.",
		"<u>Whose</u> book is on <u>our</u> desk?",
		"The house is theirs and <u>its</u> paint is flaking.",
		"Is <u>his</u> car really that fast?",
		"The money was really <u>theirs</u> for the taking.",
		"We shall finally have what is rightfully <u>ours</u>.",
		"Their mother gets along well with <u>yours</u>.",
		"I never did find out <u>whose</u> that was.",
		"What's <u>mine</u> is yours, my friend.",
		"<u>Her</u> timing couldn't have been less appropriate.",
		"The dog is <u>mine</u>.",
		"The cat is <u>yours</u>.",
		"<u>My</u> house is small.",
		"<u>Our</u> house is big.",
		"<u>Its</u> color is red.",
		"The ring is <u>hers</u>.",
		"The bag is <u>theirs</u>.",
		],
		"Indefinite Pronoun":[
		"<u>Everyone</u> has already voted.",
		"<u>No one</u> should enter without knocking.",
		"That ice-cream was good. Can I have <u>another</u>?",
		"Can <u>anyone</u> answer this question?",
		"The doctor needs to know if you have eaten <u>anything</u> in the last two hours.",
		"<u>Each</u> has his own thoughts.",
		"Do you want tea or coffee? I don't mind. <u>Either</u> is good for me.",
		"<u>Enough</u> is enough.",
		"They have no house or possessions. They lost <u>everything</u> in the earthquake.",
		"<u>Little</u> is known about his early life.",
		"<u>All</u> is forgiven.",
		"<u>Few</u> have ever disobeyed him and lived.",
		"<u>Many</u> have come already.",
		"I'm sure that <u>others</u> have tried before.",
		"John likes coffee but not tea. I think <u>both</u> are good.",
		"<u>Some</u> have arrived tonight.",
		],
		"Interrogative Pronoun":[
		"<u>Which</u> is your choice?",
		"With <u>whom</u> were you playing video games?",
		"<u>Who</u> told you?",
		"<u>Whom</u> did you tell?",
		"<u>What</u>'s happened?",
		"<u>What</u> do you want?",
		"<u>Which</u> came first?",
		"<u>Which</u> will the doctor see first?",
		"<u>Whose</u> hasn't arrived?",
		"<u>Whose</u> did you find?",        
		],				
		}, qprompt="Identify the kind of pronoun underlined below:",qsection="Pronoun Identify")

if __name__=="__main__":
	print "testing"
	print make_packet(10)