# -*- coding: utf-8 -*-
import random
import re
from nltk.corpus import wordnet as wn
from pattern.en import lemma, wordnet
def make_packet(sent_words,questions=12):
	string = ""
	s=[]
	words = sent_words #.strip().split("\n")
	random.shuffle(words)
	for word in words[:questions]:
		print word
		choices = [w for w in words[:] if w != word]
		random.shuffle(choices)
		s = ["Vocabulary"]
		s+= ["Identify the correct word for the underlined word in the following sentence"]
		try:
			syn = random.choice(get_synonym_words(word))
		except:
			syn="_"*8
		syn = syn.encode('utf-8')
		compiled_sent = re.compile(re.escape(word), re.IGNORECASE)
		#print syn,word
		prepared_sent = compiled_sent.sub("<u>"+syn+"</u>",random.choice(vocab_sentences[word]))
		#print prepared_sent
		s+=[prepared_sent]+[word]
		s+=[c for c in choices[:4]]
		#print s
		string+='\t'.join(s)+"\n"
	return string

def get_synonym_words(word):
	syns_list = []
	word = word.encode('utf-8')
	#print word
	if len(word)>2:
		syns = wn.synsets(lemma(word))
		if not len(syns):
			syns = wn.synsets(word)
		#print syns,lemma(word)
		#print "syns",syns
		for syn in syns:
			if syn.name not in syns_list:
				#print "syn lemma names", syn.lemma_names
				syns_list+=syn.lemma_names()
				#print syns_list
			
			for h in syn.hypernyms():
				syns_list+=h.lemma_names()
			#for holo in syn.hyponyms():
			#	syns_list+=holo.lemma_names
	#print "final syn list",syns_list
	return [w.replace("_"," ") for w in syns_list if w not in [word]]

vocab_sentences = {
"adjacent":[],
"foretaste":[],
"interminable":[
	"Here, a good map means the difference between a pleasant drive and an interminable one.",
	"Alternatively, some of us poor souls would prefer voluntary euthanasia to pointless interminable suffering when the time comes.",
	"To pile up honey upon sugar, and sugar upon honey, to an interminable tedious sweetness.",
	"Perpetual irritation of his mucous membranes by interminable inhalations of cigarette smoke had not yet begun.",
	"In all the barracks meetings every night, and all day long interminable hot arguments.",
],
"sullen":[],
"alight":[],
"germinate":
[
"Seeds intended for foodstuffs could spill, germinate and grow, allowing their genes to enter the ecosystem unintentionally.",
"The hot pepper seeds in the droppings germinate right there and this is an ideal shady spot for them to grow.",
"Seeds germinate quickly and plants grow with little fuss.",
"Themes are made up on the spot, and ideas that germinate in different sections of the band slowly grow and intertwine.",
"Witch hazel seeds commonly take up to two years to germinate, then even then grow slowly and unpredictably.",
],
"interrogate":[
"At one time he ordered the defense to interrogate veniremen in groups.",
"We learn to interrogate arguments and to criticize the work of those who have explored a body of research before us.",
"He began to alternately yell at and interrogate the driver.",
"Yes, you travel to new locations, then interrogate suspects.",
"In some ways, perhaps, it is best not to interrogate a legend too closely.",
],
"trickle":[],
"barren":[],
"humdrum":[
	"Some are aggressive achievers in otherwise humdrum industries.",
	"More encouraging still is that such humdrum topics as septic systems and cow-dung fires rose to the top of the agenda.",
	"But there's something about travel that turns the humdrum chore of keeping my clothes clean into an act of pure pleasure.",
	"As the author herself points out in the paper, this is a fairly humdrum result.",
	"The previously humdrum yard has become the ultimate space for entertaining and family fun.",
],
"recompense":[
[],
],
"trivial":[],
"disrupt":[],
"hurtle":[],
"renovate":[],
"truce":[],
"dynasty":["His dynasty was in ruin after the mongols invaded.",
"The dynasty was going to be destroyed, and the empire was going to fall."],
"insinuate":[],
"vicious":[],
"available":[],
"firebrand":[],
"indispensable":[],
"poised":[],
"cater":[],
"hazard":[],
"lubricate":[],
"regime":[],
"customary":[],
"homicide":[],
"mutual":[],
"retard":[],
"dissuade":[],
"indifference":[],
"pelt":[],
"transparent":["Be completely transparent with me, did you do that terrible crime?",
"She was very transparent, he could see through all of her lies."],
"entrepreneur":[],
"indignant":[],
"plague":[],
"unscathed":[],
"animated":[],
"goad":[],
"luster":[],
"singe":[],
"brood":[],
"indulge":[],
"miscellaneous":[],
"unique":[],
"culminate":[],
"ingredient":[],
"oration":[],
"upright":[],
"downright":[],
"literate":[],
"peevish":[],
"verify":[],
"drone":[],
"loom":[],
"seethe":[],
"yearn":[],
"alliance":[
"Hilden desired a closer alliance with his people from the kingdom of Dierdirien, but enemy kingdoms divided Tiyan from the mountain kingdom.",
],
"fruitless":[
"Protests that the evidence against him was flawed proved fruitless.",
"Often those lines of reasoning that seem promising to one expert look obviously fruitless to another.",
"But his career fizzled with a succession of fruitless auditions, dwindling freelance gigs and mounting debt.",
"One cannot help but wonder why he wastes his time on such a meaningless and fruitless endeavor.",
"Initially, the crew tried to carry out this operation by helicopter, but two efforts were fruitless.",
"The amount of likely fruitless speculations is downright depressing.",
"Many if not all of these behaviors are controlled by specific genes, chiefly two known as fruitless and dissatisfaction.",
"The pursuit of socialist equality by spending had proved as fruitless as by common ownership.",
"The majority of the sighs occurred in the breaks between fruitless attempts at solving the puzzles.",
"Which means honest-to-goodness energy weapons might actually become a military reality, after decades of fruitless searching.",
"Efforts were made to run the vessel on the bank but it proved fruitless.",
"Which is why discussions about these things are usually fruitless.",
"And his brief stab at profiting from his hobby by charging a subscription fee proved fruitless.",
"Teaching disease avoidance techniques is almost fruitless if the student is oblivious to basic germ-theory.",
"The endless striving for improvement was made to seem hollow, fruitless.",
"Too much money is spent on fruitless attempts to stop the production of illicit drugs.",
"But after many fruitless appeals, he recently won a round in court.",
"Advice to dine early in order to miss the crowd would be fruitless.",
"We are much afflicted now by tedious, fruitless controversy.",
"After several fruitless hours, they stopped in a gully that had been searched twice before, yielding nothing.",
"Unfortunately, attempts to find the afterglow and therefore the source of short gamma-ray bursts proved fruitless.",
"On the other hand, all experiments to date to directly detect dark matter have been fruitless.",
"My attempts to disguise myself were generally fruitless, and maybe it was due to their recognition of the mirror pole.",
"We already have a weapons proliferation problem, the trick is to convince everyone that using them is fruitless.",
"For freedom is not fruitless, but prolific of higher things.",
],
"mortify":[
"These modern fables portray an antihero whose faults always mortify him.",
"If so, his leg cannot be amputated, and will soon mortify in this climate.",
"Our readers but too well remember the mortify-ing result of all this swaggering.",
],
"spirited":[
"Ultimately, it comes off as inappropriate and a little mean spirited.",
"It has been a good spirited and enlightening discussion.",
"Shallow studies, mean-spirited, questionable conclusions.",
"Sarcasm can be mean-spirited and is therefore not allowed.",
"Done in the name of the common good and spirited in living.",
"Honest and spirited writing that makes this book a compelling read, and one that could melt public ambivalence.",
"Museums resisted those claims, demanding evidence that the contested artifacts had indeed been spirited away.",
"Tanning's artistic evolution has adhered to this spirited motto.",
"Your mean-spirited evaluations may be from students who regard you as a gender-role violator.",
"His spirited defense of the social safety net won him friends and enemies.",
"Only the truly mean-spirited will seek out a fight with a junior scholar.",
"One nasty, offensive, mean-spirited little word should not be allowed to defeat the real education of our students.",
"The debate was spirited with strongly held views on both sides.",
"My new approach is to ignore these mean-spirited attacks.",
"On one occasion he had a fight with a drunken and reckless driver who was urging to top speed a spirited horse.",
"It was a process that went on chiefly in a small world of prosperous and independent-spirited people.",
"The spirited horse, which will of itself strive to beat in the race, will run still more swiftly if encouraged.",
"They are the terror of all those driving or riding spirited horses-Times.",
"Handling is firm and steering is precise, if a bit numb for spirited driving.",
"So it's good that people see the scientific debate here is messy and spirited and confusing and even sometimes a bit nasty.",
"Read about those things and much more in the spirited interview below.",
"As with the previous swords, the blade is firm enough for a spirited duel but won't do any permanent damage.",
"Another mean-spirited takedown will surely follow, and then another, and another.",
"Conversation becomes spirited, stories are being told, digressions occur.",
"True, there is something mean-spirited about profiting from a neighbour's misfortune, but that's not worthy of outrage.",
],
"bewilder":[
"Together they manage to excite and bewilder practically all concerned.",
"Academic homonyms bewilder prospective students and bookies alike.",
"Still, there will be plenty of others with the skills to bewilder and beguile.",
"The many facets of characterization and the varied steps required to express them could bewilder dancers.",
"Icons of flame and rubble made no sense to me, and there was enough smoke in the air to bewilder anyone.",
"Whatever the intention, the campaign's conclusion seemed to bewilder politicians as much as its beginning.",
"At its highest level, wine can bewitch and bewilder, transfix and inspire.",
"Stimulate and bewilder us, frustrate and entertain us.",
"Unavoidably, some of the information may conflict with others and bewilder the public.",
"They affect to appeal wholly to reason, and bewilder themselves in the miserable snare of materialism.",
"The rash of regulations affecting packagers and packages continues at a sometimes bewilder- ing pace.",
"His sporadic mind and style bewilder and weary the reader who has not agile faculties and wealthy.",
],
"hostile":[
"Yet the hostile takeover under way here is not strictly mob related.",
"Two of my dinner talks started and ended in an hostile manner.",
"On the whole they have moved independently along separate lines, and have at times seemed indeed almost hostile to each other.",
"The effort would be unlikely to placate his most hostile critics.",
"So far, all your comments have been gratuitously critical if not downright hostile toward males.",
"For a Western journalist, the conditions were hostile and forbidding.",
"The distance was about three hundred and thirty miles through a hostile country.",
"Both promised to change the tone in Washington from hostile to conciliatory.",
"I'm not being hostile or defensive.",
"He behaved with hostile courtesy, as though he were afraid of coming closer to people he did not respect.",
"The world is no longer divided into two hostile camps.",
"The people who were left behind struggled to feed themselves in a landscape that had turned suddenly hostile.",
"As has happened too often recently, the natives could also be hostile, she warned.",
"Respond to a question that sounds hostile in a way that conveys empathy with the interviewer's concern.",
"Incidentally, these people who have expressed this opinion apparently get extremely hostile evaluations.",
],
"orthodox":[
"According to orthodox science, this can occur only under extreme conditions, as in stars or nuclear reactors.",
"The apostates signalized themselves above others by the cruelties which they exercised upon the orthodox.",
"The chimneys in tenement-house alleys were never built on a plan generous enough to let him in in the orthodox way.",
"They also include theologians representing a variety of religions and views, from orthodox to progressive.",
"Xu was candid about the skepticism, even disdain, that his proposal engenders among orthodox archaeologists.",
"Their views can rapidly shift from being considered deviant to being considered orthodox.",
"More orthodox measures aimed at limiting the franc's rise have proved ineffective.",
"Here is an example of a problem with orthodox economic belief.",
"Yet contrary to repeated forecasts of doom from orthodox economists, the economy is roaring.",
"Orthodox taxation principles would suggest that the rate be cut and the base broadened to raise legitimacy and compliance.",
"That's not about materialism vs dualist or orthodox religious conception of the mind, either.",
"The quest for the last undiscovered particle of orthodox physics has an aura of glory and pure truth to it.",
"Seriously, this is orthodox, mainstream climate physics.",
"But that piece of orthodox wisdom must be the beginning and not the end of a philosophy of legislation and enforcement.",
"My own objection to his psychology was a quite orthodox one.",
],
"virtual":[],
"buffoon":[],
"inflammable":[
"His choreography and direction burn up superlatives as if they were inflammable.",
"The shock scattered its glowing contents through the car, and in an instant the highly inflammable woodwork was blazing.",
"Then it came to be believed that small fires could sometimes be a useful tool, keeping inflammable underbrush in check.",
"Petrol, another established solvent, is highly inflammable.",
"The authorities said an inflammable liquid was thrown through a window.",
"Vandalising pipes carrying inflammable liquid is hazardous.",
"It is generally believed that the rebels there have burned everything of an inflammable nature.",
"They have modified electrolytes that are inflammable.",
"For better fire protection, they are used instead of easily inflammable mineral oil based fluids in zones exposed to fire risks.",
"He collected some of this gas and discovered that it was inflammable.",
"Transporters of bulk inflammable liquids or compressed inflammable gases will not carry flame-producing signals.",
"Garments and household items prepared from cotton are inflammable.",
"The pine and the fir trees are highly inflammable because of the pitch they contain.",
],
"procure":[
"Many find ways to procure cheaper produce, even to live off the land with tiny plots they stake out outside the towns.",
"The obvious choices--a spaceship, an orchard, glittering jewels--prove too difficult to procure.",
"Meanwhile his institution and others are working to procure good data.",
"When he did procure prime ingredients — fresh tofu from Chinatown, for example — the variations were legion and sublime.",
"In this latter assignment I had to procure my own piling and took a small detachment to cut timber in the jungle forests.",
"This is they must procure a dispensation from local ecclesiastical authorities.",
"Such early sales help a developer procure financing for a project.",
"Some global companies may be able to procure supplies from elsewhere.",
"Thus by all means that may be they procure to have gold and silver among them in reproach and infamy.",
"Of all the components used, the magnet may be the most difficult to procure.",
"Insist on careful documentation at every step, circulate information to all parties of the search, and procure signatures.",
"Presumably, you drove there to procure the various necessities that support your life and well being.",
"In an effort to allow families to procure building materials gradually, self-storage locker systems have been proposed.",
"If a creditor refused it, the debtor could deposit the bills with the court and procure his discharge.",
"Only people with money could go to university and the texts they studied there were expensive to procure.",
],
"void":[
"Bankruptcy would have made the contracts null and void, at best in line with all the unsecured creditors.",
"These intentionally confusing spaces are created in part by a long void that cuts through the length and height of the museum.",
"Not surprisingly, three decades later there is no shortage of observers rushing to fill the void with all sorts of explanations.",
"The difference between manufacturing and services is not an ontological void between making things and not making things.",
"When one firm shuts a factory, the other cannot fill the void quickly.",
"Why would anyone want to buy a property and pretend to live in such a controlling, unfair and culturally void state.",
"Running liners is a business that must return a profit, and be as void of sentiment as running trains.",
"The fact that his career was so short-he went mad at twenty-nine-makes this void more painful.",
"Relying on growth in this way might be fine if the global economy existed in a void, but it does not.",
"It makes sense that matter would spread to fill the void beyond it's perimeter.",
"Think about the void in the structure that the impact and initial explosion created.",
"Our frozen alarm and fascination carried us into the void of the dead tenement.",
"The teacher helps fill a void left by the student's absent father.",
"These drugs offered oblivion, not ethereality, a rush into the void rather than a slow drifting to blissful serenity.",
"His loss leaves a void in our lives that will never be filled.",
],
"controversial":[
"Human beings are proud of what they create-no matter how controversial or deadly.",
"Their attendance-or lack thereof-has been controversial recently.",
"We understand that it will be controversial to release these photographs.",
"It was a controversial notion, but not an unpopular one.",
"The fitful evolution of bacteria supports a controversial theory.",
"Although the evidence remains controversial, he is convinced that the radiation poses a risk to human health.",
"The approach protects controversial areas of study and allows the state to account for costs over decades instead of every year.",
"Even if that is the case it is controversial to say it came from a country.",
"The aim of the article is to inform the reader about this controversial, yet highly quixotic idea.",
"The idea is controversial, though many panelists said they would support it, provided it wasn't the only outcome measure.",
"Those factors reflect the controversial nature of foreign-student enrollment, especially in the sciences.",
"In the realm of high-stress admissions and licensing exams, the accommodation question is as controversial-and complex-as ever.",
"In that extremely controversial study, researchers used a wide range of methods to subject mice to various levels of pain.",
"Its hosts should strive for broadmindedness while approaching controversial news topics with disclosed and well-understood biases.",
"Which framework is better is a far more complicated and controversial question.",
],
"inflict":[
"Major league baseball isn't the only sport ready to inflict serious damage to itself this summer.",
"Such signs point to a department with serious internal issues and, worse, chomping to inflict their unhappiness on a newcomer.",
"Another of the aims of terrorism is to inflict economic damage, so weakening the target government.",
"As for the suggestion that scientists purposely inflict harm on animals with the only goal of profiting.",
"Not only are they cruelly torturing cats, but also all the wildlife that they inflict their cats upon.",
"They have a long muzzle and sharp fangs designed to inflict deadly injury.",
"It takes panache to play a large outdoor carillon and inflict your art, unbidden, on a neighborhood.",
"Katrina taught us what devastation extreme weather can inflict on colleges.",
"These fish also inflict their venoms with a delivery mechanism.",
"Freedom does not mean inflict damage, not on yourself nor onto someone else.",
"It is also the correct term to apply to anyone on whom you might inflict it as a gift.",
"But financial crises tend to inflict a lot of damage on capacity.",
"They also inflict a painful rash on any human who handles them.",
"Animals will be in pain when humans inflict cruelty on them.",
"With a keystroke, he can inflict all sorts of complications, overriding any preprogrammed instructions.",
],
"scurry":[
"Scurry dived to her left, got a hand on the ball but could not keep it out of the net.",
"On campus you scurry past us in the halls, being careful not to learn our names.",
"Lizards can scurry across ceilings and dash across water.",
"Insects, spiders and other tiny monsters that scurry across floors or fly through the air are frightening enough.",
"Scurry couldn't catch a cold in that game and is so old she can't even get a goal kick past half field.",
"We are now watching the rats scurry about before they start jumping.",
"Snakes, crocodiles, and crabs scurry and swim about the forest floor.",
"Of course all of these have been show to you repeatedly and all you do is scurry off.",
"The field marshal in charge of the rocket base looks on, while launch pad workers scurry in the upper left background.",
"They can't fly, but they can scurry quite quickly over floors, walls and ceilings.",
"More companies than before now plan to avoid a last-minute scurry.",
"Few things make publishers and agents scurry away faster than short stories.",
"Press the corresponding button on this repeller, and the critter will scurry away.",
"Pine martens scurry along high branches, sniffing the air for small rodent prey.",
"Let him leave the few furry and feathered inhabitants of our city alone to scurry and scamper and provide a morning bird song.",
],
"wayward":[
"So, claims about new technology and wayward kids shouldn't be taken too seriously.",
"The central government claims it can enforce its wishes over wayward local administrations.",
"Trickles of wayward meteors are visible year-round in any clear night sky.",
"New research finds adultlike structure in the brains of wayward youths.",
"Need little pruning except to remove wayward or dead growth.",
"Perhaps you have not yet experienced the impact of being on the receiving end of wayward professors.",
"But there is also much unease about the taxpayer paying billions to take control of wayward businesses.",
"Kangaroo pockets that sit on a wide self-fabric hem hold the contents of a wayward life.",
"It sat vacant and boarded up, used only as a home for wayward pigeons.",
"For a while, it even became a temporary home to wayward cattle.",
"He broke off a branch, waved it in the air, then trotted back to his wayward females.",
"For the first time, the government has forced the departure of a wayward banker.",
"The courts begin to hold the company liable for all sorts of wayward transactions.",
"But the younger sons and the flocks of daughters, nieces and cousins were much more wayward.",
"These are sticky bits of a wayward protein called beta-amyloid that gum up the spaces between nerve cells.",
],
"dishearten":[
"Those loud students would dishearten any teacher, but especially a conscientious apprentice.",
"Ambivalent relationships may do more than dishearten.",
],
"malignant":[
"Many cancer treatments work by coaxing malignant cells to commit suicide, a process known to biologists as apoptosis.",
"In some cases, uncontrolled growth of neural stem cells has been linked to malignant brain tumors.",
"Too often the apparently benign civil audit is really a malignant criminal investigation.",
"He focuses on the effects of “malignant competition” that lead to profitless growth and a desperate lurch into overseas markets.",
"Exposure to radiation in large amounts will increase malignant disease; small amounts may possibly do the same.",
"It is not known whether the tumor is malignant or benign.",
"There are also malignant complications, which in his case could be a recurrence of his tumor that he was treated for.",
"No one knows precisely what factors change a normal cell into a malignant cell.",
"Tests on the tissue that was removed showed malignant cancer cells.",
"This will counter the malignant dust of biological and chemical weapons.",
"Sure enough the lesion was a malignant melanoma.",
"Malignant tumors indicate often lethal brain conditions, but even nonmalignant growths can preempt normal brain activity.",
"Two other, rarer forms also existed: hemorrhagic and malignant.",
"All six of the excised lymph nodes were malignant, a bad sign.",
"At times, the lovers seem to be fighting not only against a malignant fate but against the dying of the light.",
],
"sodden":[
"Local cadres sitting on plastic chairs stoically endure the sodden spectacle.",
"Players' sodden shoes became as fuzzy as bedroom slippers.",
"Sodden areas near creeks and marshes are the best place to find amphibians.",
"Then canyon snowdrifts melted furiously into swollen streams and sodden ground.",
"Clutches also found under small soggy logs and sodden leaf litter, and in small stump holes.",
"Pools, sodden places, or mudholes are not allowed near a well.",
"The lines of sodden, dripping tents stretched away from me in the darkness.",
"Its bald lights of red and yellow under the sodden drip of the night.",
],
"wince":[
"The pound's recent surge in the currency markets has made exporters wince.",
"The story is hackneyed and tiresome, bouncing from one witless and wince-inducing situation to another.",
"Upscale and uptight, they wince at his uninhibited folksiness.",
"The architects wince, knowing this option will be unacceptable to their clients.",
"Pedants will wince at some of his more egregious theoretical simplifications.",
"Touch a galled horse and he'll wince.",
"Many of us I'm sure look at some of our early work and wince.",
"The dialogue she gives her characters can be wince-inducing.",
"Every time someone says they saw my picture in the paper, I wince silently.",
"It could make you feel mad or excited or it could make you even cower and wince.",
"The idea of handing such decisions to outsiders might make some faculty members wince.",
"We extol critical thinking but wince to make room for a quiet period to allow it entrance.",
"Editors wince when a cover letter contains the name of a rival press in first paragraph.",
"Explain to them what it meant, the context in which it was used, and why you wince when you hear it.",
"Commercialism also sometimes involves stunts which make traditionalists wince.",
],
"anecdote":[
"He told a short anecdote about his trip the mall on Saturday.",
"To open her presentation she told a short anecdote to the crowd."],
"entreat":[
"I must entreat you to put into the hands of one or more of your ablest booksellers to dispose of them.",
"The student attempted to entreat the teacher for the answers to the test."],
"iota":["But he didn't display an iota of love toward her that I picked up on.",
"Six months of marriage had not decreased an iota the awe in which he held this woman he so loved."],
"substantial":["The changes you made to my paper airplane were substantial",
"When you edited my paper, the changes you made were substantial."],
"consolidate":[
"An example of consolidate is when you pour two half empty boxes of cereal into one big box.",
"An example of consolidate is when you strengthen your fund-raising efforts.",
"She consolidated five separate agencies into a single department.",
],
"fallible":["Sure, they were fallible people, but when did they fail?",
"And the government proved just as fallible, just as corrupt and just as oppressive as anything that had gone before it."
],
"maul":["The lion mauled the unsuspecting herd of gazelle.",
"The huge wild monster was about to maul and tear to pieces his prey."],
"tactful":[
"He was tactful about the matter, careful not to talk about the untimely death of the boys parents in front of everyone.",
"She tried to be tactful and not discuss her best friend's loss because she knew it would deeply upset her best friend."
],
"counterfeit":[
"An example of counterfeit is money that is not produced by the proper authorities.",
"Queen Edith's crown was found to be only of silver-gilt, with counterfeit pearls, sapphires and other stones.",
"This instrument was devised for the purpose of detecting counterfeit coin, especially guineas and half-guineas.",
],
"fickle":["Oh what fickle thoughts you have about love, one minute you love him and the next minute you refuse to even see him.",
"The winds can be very fickle and ever-changing when you are out at sea."],
"potential":["Everyone has the potential to succeed but some utilize this while others do not.",
"Within him was the potential for greatness that only a grand adventure could reveal."],
"tamper":["Don't tamper with evidence or disturb the crime scene in any way!",
"They caught her trying to tamper with the lock and break into the school."],
"docile":[
"You could have any woman you wanted in any time you wanted, including one who'd be far more docile than I am.",
"These creatures have a docile nature and are very easy to tame.",
"The women he remembered were docile and silent.",
],
"fugitive":["Hurry we must catch that fugitive who escaped from the law.",
"That blasted fugitive has run away and we need to chase him across the country."],
"radiant":["The moon was bright and radiant in the night's sky on this all-Hallows eve.",
"Her radiant gown brushed against the windowsill and sent sparks flying across the room."],
"ultimate":["She owned the ultimate doll, none could be better than hers.",
"He owned the ultimate action figure, no toy could be better."],
"dominate":[
"Alex did like to be in control, there was no denying that, but he certainly didn't dominate her.",
"The king wanted to dominate his subjects",
"The ruler wanted to control and dominate his kindgom."
],
"grimy":[
"Their hands and faces were all grimy from playing outside in the mud.",
"After coming back from a day in the mines, the man's hands were slick with mud and very grimy."
],
"rural":["They lived in a rural village, outside the city in the country.",
"Their life was rural, they tended to the cattle and lived in the country."],
"uncertainty":["Sometimes there can be much uncertainty in life, and there seems no clear path forward",
"Their campgain was plagued with uncertainty at every turn, no one knew what was going to happen next."],
"anonymous":[
"The citizens who gave the homeless man a new car wanted to remain anonymous and unknown.",
"The hackers wanted to remin anonymous while they broke into the governments secrets."],
"frustrate":["That experience frustrated them, there seemed to be no way to convince their teacher to move the exam date.",
"They were frustrated because the silly girls and boys would not listen to instructions."],
"pending":["This time, the answer is pending and we are waiting for the right moment to tell you.",
"The package is pending, waiting for the next ship to transport it to its next destination."],
"reluctant":[],
"browse":["They browsed the dictionary for all the words starting with an.",
"The spent hours trying to browse the large library resources for one particular book."],
"grim":["The situation was grim, they would not make it through the night without food and water.",
"Their lives were grim, they always worked from dusk til dawn with no hope of an end to the interminable toil."],
"prescribe":[],
"scrimp":[],
"dupe":["She was able to dupe and trick them right away, making them believe the stuffed tiger was actually alive.",
"One could easily dupe them and make those little ones believe almost anything. Consequently, they were always playing pranks on the little ones.",],
"inimitable":["They were inimitable unable to be copied or duplicated.",
"The boy was truly inimitable in his personality, no true equal or copy existed."],
"preview":[],
"snare":[],
"dynamic":["They were a dynamic bunch, lively and changing.",
"The environment is dynamic, changing with the years and the seasons."],
"makeshift":[],
"prominent":[],
"utmost":[],
"eradicate":["At night the aliens said they would eradicate the human race.",
"Tomorrow after she finishes lunch, the girl is going to eradicate all the bugs which live in her locker."],
"marginal":[],
"quaint":[],
"vengeance":[],
"amiss":[],
"flaw":[],
"notable":[],
"prior":[],
"brawl":[],
"fledgling":[],
"nurture":[],
"proficient":[],
"detest":[],
"fluster":[],
"paradox":[],
"salvo":[],
"domestic":[],
"foremost":[],
"perjury":[],
"vigilant":[],
"flagrant":[],
"momentum":[],
"presume":[],
"wrath":[],
"abnormal":[],
"eject":[],
"nub":[],
"prudent":[],
"capsize":[],
"flourish":[],
"onslaught":[],
"quench":[],
"catastrophe":[],
"incentive":[],
"ordain":[],
"remnant":[],
"decrease":[],
"insubordinate":[],
"outstrip":[],
"simultaneous":[],
"disputatious":[],
"legible":[],
"pervade":[],
"swerve":[],
"accelerate":[],
"entice":[],
"melancholy":[],
"quibble":[],
"bystander":[],
"erode":[],
"ordeal":[],
"ratify":[],
"canvass":[],
"flounder":[],
"parch":[],
"regal":[],
"casual":[],
"graphic":[],
"persist":[],
"stifle":[],
"downtrodden":[],
"gruesome":[],
"puny":[],
"vital":[],
"bellow":[],
"dismantle":[],
"lair":[],
"parasite":[],
"beneficiary":[],
"farce":[],
"lavish":[],
"shirk":[],
"botch":[],
"futile":[],
"morbid":[],
"surplus":[],
"clutter":[],
"grueling":[],
"notorious":[],
"timidity":[],
"dilapidated":[],
"hospitable":[],
"pamper":[],
"veto":[],
"adequate":[],
"havoc":[],
"lax":[],
"overture":[],
"ajar":[],
"hearth":[],
"mar":[],
"pact":[],
"dialogue":[],
"implore":[],
"misdemeanor":[],
"stalemate":[],
"emblem":[],
"infamous":[],
"mull":[],
"vindictive":[],
"gigantic":[],
"innumerable":[],
"narrative":[],
"wilt":[],
"abound":[],
"embezzle":[],
"mellow":[],
"rant":[],
"braggart":[],
"heartrending":[],
"nomadic":[],
"reinforce":[],
"cache":[],
"leisurely":[],
"piecemeal":[],
"seclusion":[],
"clarification":[],
"lethargic":[],
"quest":[],
"status":[],
"despondent":[],
"malady":[],
"random":[],
"turmoil":[],
"agitation":[],
"enchant":[],
"hilarious":[],
"pall":[],
"blurt":[],
"fluctuate":[],
"ignite":[],
"reputable":[],
"chronological":[],
"foster":[],
"magnitude":[],
"revere":[],
"countenance":[],
"grovel":[],
"massive":[],
"saga":[],
"diminish":[],
"handicraft":[],
"maternal":[],
"stodgy":[],
"affliction":[],
"gaudy":[],
"impostor":[],
"oppress":[],
"akin":[],
"gratitude":[],
"inflate":[],
"pedestrian":[],
"cosmopolitan":[],
"heed":[],
"meager":[],
"transmit":[],
"elongate":[],
"hoax":[],
"meditate":[],
"vanquish":[],
"gala":[],
"impartial":[],
"nutritious":[],
"wan":[],
"authoritative":[],
"despot":[],
"hoard":[],
"officiate":[],
"bankrupt":[],
"feud":[],
"indisposed":[],
"partial":[],
"clamor":[],
"haggle":[],
"legacy":[],
"patronize":[],
"coincide":[],
"hardy":[],
"legitimate":[],
"rite":[],
"cynical":[],
"harmonious":[],
"mirth":[],
"sagacious":[],
}

vocab = """humdrum
interminable
germinate
interrogate
alliance
anecdote
entreat
iota
consolidate
fallible
maul
counterfeit
fickle
potential
docile
fugitive
radiant
dominate
grimy
"""
#print make_packet(vocab)
#print vocab_sentences.keys()

#for vocab_sentences()